### PR TITLE
Added apigenPath option, bumped version to 0.1.3, fixed README and fixed github path

### PR DESCRIPTION
**Pull request by daN4cat**
npm package should be updated once merged

### CODE REVIEW

**Review by jjeaton — APPROVED** [review]
Thanks! I'll get this merged soon and push it up to npm.

**Comment by daN4cat** [comment]
I can't remember but maybe there is an automatic way to connect npm package to GitHub and fetch packages tagged with newer versions once released.
I might confuse that with php composer but I would suggest to check if that options is available so you get everything automated.

Last note, I'm not sure the Todo list in the readme is totally correct. More options and test yes, the first point I'm not sure but I leave to you.

**Comment by daN4cat** [comment]
@jjeaton any chance you can get this PR sorted and npm updated? Thanks

**Review by jjeaton — APPROVED** [review]

**Comment by jjeaton** [comment]
@daN4cat thanks! and sorry for the delay, I've published 0.1.3 to npm.

**Pull request merged**
